### ISSUE TITLE
Outdated docs

### ISSUE THREAD

**Issue by AndiZeta** [gorilla-co/odata-query#22]
Hi,
    I am starting using odata-query for a project (Thanks!) and I noticed that the links in the docs are broken Is it OK if I make a PR with the updated links?
   So far, I have noticed just a couple of places:
 - PyPi page "contributing guidelines"
 - readthedocs "Reporting a bug" link to issues

**Comment by OliverHofkens** [comment]
Good catch! 
I'd be happy to accept a PR fixing these, thank you very much!

**Comment by AndiZeta** [comment]
Fixed by #23
