### ISSUE TITLE
Remove Athena specific code

### ISSUE THREAD

**Issue by OliverHofkens** [gorilla-co/odata-query#26]
The AST to SQL transformer still contains some Athena-specific code. Ideally this library contains a pure, generic SQL transformer, and an Athena/Presto dialect can be maintained in a seperate library/extension.

**Comment by meitham** [comment]
Hi Oliver, I have code based on Athena that renders odata ast into sqlite specefic syntax.  I was going to make a PR to push here but noticed this issue you raised to remove Athena alltogether.  Have you decided on how to maintain odata extensions into separate packages?  If not may I suggest Pluggy (Pytest's own extension system) https://pluggy.readthedocs.io/en/stable/index.html

Until the plugin architecture is ready, do you think it's worth me raising a PR to get sqlite support added here?  And do you have update on when version 0.7 is going into pypi?

Many thanks

**Comment by OliverHofkens** [comment]
Hey @meitham, 

Thanks for the PyPI reminder, I just published v0.7!

Pluggy looks cool, didn't know about that. I think in the short term I'd happily accept a sqlite contribution, we don't need to worry about a plugin system urgently as the package is still pretty small. I guess it would also make this Athena/generic split easier once we have sqlite, since we have a better view of what makes the dialects unique.

**Comment by OliverHofkens** [comment]
Done and released in v0.8.0 ✅
