### ISSUE TITLE
Maybe add contributing guidelines to readthedocs

### ISSUE THREAD

**Issue by cblegare** [gorilla-co/odata-query#3]
Hello again!

May I suggest you add your nice contributor's guide to the read the docs?  This can be done without duplicating the documentation's source:

1. Convert (manually) `CONTRIBUTING.md` to RestructuredText as `CONTRIBUTING.rst` (Github will still render it just fine as HTML).

2. Add a `contributing.rst` file to your doc and add it somewhere to the doctree with the following content:
  
  ```rst
  .. _contributing:

  .. include:: ../CONTRIBUTING.rst
  ```

3. There is no third step!

**Comment by cblegare** [comment]
I see you depend on the MyST parser for the docs, so you may not have to convert md -> rst.  I also see it is only used to include the `README.md` in [docs/index.md](docs/index.md).  One could prefer to simply convert README.md to README.rst an remove the MyST parser, Github will manage this just fine.

**Comment by OliverHofkens** [comment]
This is now done and live with the newly released v0.4.2: https://odata-query.readthedocs.io/en/latest/contributing.html
One minor note: `Pypi` refuses packages with unparseable `README`'s, so I had to remove the Sphinx `:ref:` to the contributing page there. 
Thanks for helping us improve this package!
