### ISSUE TITLE
`AstToSqlVisitor` can not handle a function call as right hand side of contains-filter

### ISSUE THREAD

**Issue by d2a-pnagel** [gorilla-co/odata-query#47]
Steps to reproduce:
* Try to translate `contains(tolower(name), tolower('A'))` to SQL using the `AstToSqlVisitor` 
-> error:
```
 AttributeError("'Call' object has no attribute 'val'")
```

Bug spotted:
* `AstToSqlVisitor._to_pattern` does not take into account that the `arg` could be an `ast.Call` (and assumes a literal in the `else` branch)

Proposed solution:

Change
```
  if isinstance(arg, ast.Identifier):
```
Into
```
  if isinstance(arg, ast.Identifier | ast.Call):
```

**Comment by OliverHofkens** [comment]
Hi!
Thanks for the very clear and concise report, reproducer ánd proposed fix. What a blessing!
PR #49 contains the fix and a lot of test cases to cover it. Once reviewed, I'll include it in a new release (0.9.1).

**Comment by OliverHofkens** [comment]
Should be live in [v0.9.1](https://pypi.org/project/odata-query/#history)!
