### ISSUE TITLE
odata geospatial properties

### ISSUE THREAD

**Issue by srepmub** [gorilla-co/odata-query#48]
hi!

we are trying to make use of geospatial queries, as described here:

https://www.odata.org/blog/geospatial-properties/

it seems though that the "geography'..'" syntax is not yet accepted, resulting in:

odata_query.exceptions.ParsingException: Failed to parse at: Token(type='STRING', value=String(val=''), lineno=1, index=38)

working around this, calling geo.intersects() in a query results in the following:

odata_query.exceptions.UnknownFunctionException: Unknown function: 'intersects'

(in grammar.py it compares 'intersects' with 'geo.intersects', so no match..?)

working around this as well, it appears there is no conversion to django geo calls as of yet (no djangofunc_intersects?).

is it correct to say that geospatial queries are not really supported at the moment? :)

**Comment by srepmub** [comment]
(I'd be interested in working on a PR, but thought I'd check first ;))

**Comment by OliverHofkens** [comment]
Hi @srepmub!
Indeed, geospatial syntax and queries aren't implemented yet.
Feel free to give it a shot, we appreciate it!

**Comment by OliverHofkens** [comment]
Merged and released! Currently still under a beta version `0.10.0b1` since I'm a bit paranoid about breaking people's code with the system library stuff. But at least we can start testing this live now!
