### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by rominf** [gorilla-co/odata-query#52]
I am Fedora packager of python-odata-query.

Up until v0.8.1 releases were marked with tags. Last two releases are not marked with tags. This prevents from running https://packit.dev/ to automate releases: it picks up v0.8.1 as latest release.

Could you please introduce release tagging back?

**Comment by OliverHofkens** [comment]
My bad, thanks for letting me know!
I pushed the missing tags 👍
