### ISSUE TITLE
Support for Year and Month in a Duration

### ISSUE THREAD

**Issue by nickybulthuis** [gorilla-co/odata-query#54]
We need support for durations specified in Years and Months. Currently, the implementation supports durations up to days. 

What we need is something like this:

| Odata | SQL | 
| --- | --- |
| period_start add duration'P1Y' ge period_end | "period_start" + INTERVAL '1' YEAR >= "period_end" |
| period_start add duration'P2M' ge period_end | "period_start" + INTERVAL '2' MONTH >= "period_end" |

I've created an PR for this: https://github.com/gorilla-co/odata-query/pull/53

(first time, not sure yet how to link a PR to an Issue)

**Comment by OliverHofkens** [comment]
Hey, thanks for both the feature request and pull request, looks great!

One thing I noticed is that year and month durations are not officially in the OData spec (or I can't find them).
The ABNF lists the following rule for `duration`:
```
duration      = [ "duration" ] SQUOTE durationValue SQUOTE
durationValue = [ SIGN ] "P" [ 1*DIGIT "D" ] [ "T" [ 1*DIGIT "H" ] [ 1*DIGIT "M" ] [ 1*DIGIT [ "." 1*DIGIT ] "S" ] ]
```

That doesn't mean I'm opposed to adding it though, if it brings value to users it is more than welcome.
Maybe we need a page in the documentation for instances where we deviate from the official spec!
