### ISSUE TITLE
Unused dependencies in testing

### ISSUE THREAD

**Issue by rominf** [gorilla-co/odata-query#6]
While packaging your library for Fedora (see https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2031000), I've noticed that `Faker` and `moto` from testing extra are not used. Please consider removing them from the requirements.

**Comment by OliverHofkens** [comment]
Great catch, thanks for reporting!
I've removed the dependencies and published a new version without them (0.4.2).
Also, really cool to hear that you're packaging our library for Fedora, thanks for that!

**Comment by rominf** [comment]
Since you've told that it's really cool :-), I'm happy to give an update about the Fedora packaging: packages are in stable repositories of Fedora, see https://packages.fedoraproject.org/pkgs/python-odata-query/python3-odata-query/
